### ISSUE TITLE
crash on startup of balatro with Cardsauce mod

### ISSUE THREAD

**Issue by Lima7T** [BarrierTrio/Cardsauce#10]
Context : I installed the cardsauce mod with lovely and steammodded injector 1.0.0, my install is NOT fresh I had already cryptid and talisman installed but I removed every mod other than cardsauce to assure that there will be no mod incompatibilty. I also did reset my profiles so there wouldn't be any save issues

When I start the game it crashes and I get that error message : 

Oops! The game crashed:
[SMODS Cardsauce "main.lua"]:1307: attempt to index a nil value

Additional Context:
Balatro Version: 1.0.1n-FULL
Modded Version: 1.0.0~ALPHA-1021a-STEAMODDED
Love2D Version: 11.5.0
Lovely Version: 0.6.0
Steamodded Mods:
    1: Cardsauce by BarrierTrio/Gote & Keku [ID: Cardsauce, Version: 1.0, Uses Lovely]
Lovely Mods:

Stack Traceback
===============
(3) main chunk of file 'main.lua' at line 1307 (from mod with id Cardsauce)
(4) Lua local 'func' at Steamodded file 'loader/loader.lua:308' 
(5) Lua field 'with_compat' at Steamodded file 'core/compat_0_9_8.lua:522' 
Local variables:
 func = Lua function '?' (defined at line 306 of chunk [SMODS _ "loader/loader.lua"])
 localization_ref = table: 0x3f62b040  {descriptions:table: 0x3f62b0a0, tutorial_parsed:table: 0x3f368c28, quips_parsed:table: 0x3f2e0170 (more...)}
 captured_loc = table: 0x3f3519e0  {}
(6) Lua global 'loadMods' at Steamodded file 'loader/loader.lua:306' 
Local variables:
 modsDirectory = string: "C:\\Users\\frede\\AppData\\Roaming\\Balatro\\Mods"
 header_components = table: 0x3f9074b0  {version:table: 0x3f9080a8, id:table: 0x3f907850, conflicts:table: 0x3f907f98 (more...)}
 used_prefixes = table: 0x3f908260  {csau:Cardsauce}
 lovely_directories = table: 0x3f908288  {1:C:\Users\frede\AppData\Roaming\Balatro\Mods/Cardsauce/}
 processDirectory = Lua function '?' (defined at line 66 of chunk [SMODS _ "loader/loader.lua"])
 keyset = table: 0x3f28d558  {1:0}
 check_dependencies = Lua function '?' (defined at line 237 of chunk [SMODS _ "loader/loader.lua"])
 (for generator) = C function: builtin#6
 (for state) = table: 0x3f28d558  {1:0}
 (for control) = number: 1
 _ = number: 1
 priority = number: 0
 (for generator) = C function: builtin#6
 (for state) = table: 0x3f9bffe8  {1:table: 0x3f9b8178}
 (for control) = number: 1
 _ = number: 1
 mod = table: 0x3f9b8178  {version:1.0, id:Cardsauce, main_file:main.lua, lovely:true, can_load:true (more...)}
(7) Lua global 'initSteamodded' at Steamodded file 'loader/loader.lua:387' 
(8) Lua method 'start_up' at file 'game.lua:211'
Local variables:
 self = table: 0x3f2fd158  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, F_ENGLISH_ONLY:false (more...)}
 settings = string: "return {[\"version\"]=\"1.0.1n-FULL\",[\"reduced_motion\"]=false,[\"paused\"]=false,[\"QUEUED_CHANGE\"]={},[\"COMP\"]={[\"score\"]=2885080,[\"name\"]=\"\",[\"prev_name\"]=\"\",},[\"colourblind_option\"]=false,[\"play_button_pos\"]=2,[\"CUSTOM_DECK\"]={[\"Collabs\"]={[\"Spades\"]=\"collab_SK\",[\"Hearts\"]=\"collab_TBoI\",[\"Diamonds\"]=\"collab_EG\",[\"Clubs\"]=\"collab_STS\",},},[\"crashreports\"]=false,[\"tutorial_progress\"]={[\"completed_parts\"]={[\"first_hand\"]=true,[\"first_hand_3\"]=true,[\"second_hand\"]=true,[\"big_blind\"]=true,[\"first_hand_4\"]=true,[\"small_blind\"]=true,[\"first_hand_section\"]=true,[\"first_hand_2\"]=true,[\"shop_1\"]=true,},[\"section\"]=\"second_hand\",[\"hold_parts\"]={[\"first_hand_3\"]=true,[\"second_hand\"]=true,[\"big_blind\"]=true,[\"first_hand_4\"]=true,[\"small_blind\"]=true,[\"shop_1\"]=true,[\"first_hand_2\"]=true,[\"first_hand\"]=true,},},[\"language\"]=\"fr\",[\"tutorial_complete\"]=true,[\"run_stake_stickers\"]=true,[\"WINDOW\"]={[\"selected_display\"]=1,[\"display_names\"]={[1]=\"1\",},[\"screenmode\"]=\"Borderless\",[\"DISPLAYS\"]={[1]={[\"screen_resolutions\"]={[\"strings\"]={[1]=\"1920 X 1080\",},[\"values\"]={[1]={[\"w\"]=1536,[\"h\"]=864,},},},[\"screen_res\"]={[\"w\"]=1536,[\"h\"]=864,},[\"DPI_scale\"]=1,[\"MONITOR_DIMS\"]={[\"height\"]=1080,[\"width\"]=1920,},},},[\"vsync\"]=1,},[\"screenshake\"]=54.282665210939,[\"cryptid_notifs\"]={[\"jimball\"]=true,},[\"SOUND\"]={[\"volume\"]=66.522253707733,[\"music_volume\"]=67.151071133702,[\"game_sounds_volume\"]=55.064462933246,},[\"music_control\"]={[\"current_track\"]=\"\",[\"desired_track\"]=\"\",[\"lerp\"]=1,},[\"ACHIEVEMENTS_EARNED\"]={[\"card_discarder\"]=true,[\"heads_up\"]=true,[\"retrograde\"]=true,[\"royale\"]=true,[\"_100000k\"]=true,[\"cartomancy\"]=true,[\"mid_stakes\"]=true,[\"low_stakes\"]=true,[\"ante_upper\"]=true,[\"astronomy\"]=true,[\"_10k\"]=true,[\"nest_egg\"]=true,[\"legendary\"]=true,[\"shattered\"]=true,[\"ach_cry_now_the_fun_begins\"]=true,[\"_1000k\"]=true,[\"clairvoyance\"]=true,[\"ante_up\"]=true,[\"card_player\"]=true,},[\"profile\"]=2,[\"current_setup\"]=\"Continue\",[\"GAMESPEED\"]=4,[\"ambient_control\"]={[\"ambientFire1\"]={[\"per\"]=1.1,[\"vol\"]=0,},[\"ambientOrgan1\"]={[\"per\"]=0.7,[\"vol\"]=0,},[\"ambientFire2\"]={[\"per\"]=1.05,[\"vol\"]=0,},[\"ambientFire3\"]={[\"per\"]=1,[\"vol\"]=0,},},[\"DEMO\"]={[\"win_CTA_shown\"]=true,[\"quit_CTA_shown\"]=true,[\"timed_CTA_shown\"]=true,[\"total_uptime\"]=74.776768529463,},[\"GRAPHICS\"]={[\"bloom\"]=1,[\"crt\"]=67.222896730537,[\"texture_scaling\"]=2,[\"shadows\"]=\"On\",},}"
 settings_ver = nil
 new_colour_proto = table: 0x3f305668  {Spades:table: 0x3f511a68, Hearts:table: 0x3f813be0, Diamonds:table: 0x3f7b5a38 (more...)}
 sound_files = table: 0x3f4eb260  {1:ambientFire1.ogg, 2:ambientFire2.ogg, 3:ambientFire3.ogg, 4:ambientOrgan1.ogg (more...)}
 shader_files = table: 0x3f496638  {1:CRT.fs, 2:background.fs, 3:booster.fs, 4:debuff.fs, 5:dissolve.fs, 6:flame.fs (more...)}
(9) Lua field 'load' at file 'main.lua:923'
(10) Lua function '?' at file 'main.lua:870' (best guess)
(11) global C function 'xpcall'
(12) Love2D function at file 'boot.lua:368' (best guess)
Local variables:
 result = boolean: true
 main = nil
(13) global C function 'xpcall'
(14) Love2D function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])
 inerror = boolean: true
 deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])

Can someone who is acquainted with lua files explain me where the issue is ? I would be very thankful.

**Comment by Mysthaps** [comment]
Update Steamodded by completely deleting the old folder and downloading the new one [here](https://github.com/Steamopollys/Steamodded/archive/refs/heads/main.zip)
