### ISSUE TITLE
Game crashed on bootup

### ISSUE THREAD

**Issue by Snoblin34** [BarrierTrio/Cardsauce#5]
Oops! The game crashed:
[SMODS Cardsauce "jokers/speen.lua"]:6: Could not open file Mods/Cardsauce/assets/1x/jokers/speenBase.png. Does not exist.

Additional Context:
Balatro Version: 1.0.1n-FULL
Modded Version: 1.0.0~ALPHA-1220a-STEAMODDED
LÖVE Version: 11.5.0
Lovely Version: 0.6.0
Steamodded Mods:
    1: Cardsauce by BarrierTrio/Gote & Keku [ID: Cardsauce, Version: 1.0, Uses Lovely]
Lovely Mods:

Stack Traceback
===============
(3) field C function 'newImage'
(4) main chunk of file 'jokers/speen.lua' at line 6 (from mod with id Cardsauce)
(5) main chunk of file 'main.lua' at line 380 (from mod with id Cardsauce)
(6) Lua global 'loadMods' at Steamodded file 'src/loader.lua:528' 
Local variables:
 modsDirectory = string: "C:\\Users\\oshwa\\AppData\\Roaming\\Balatro\\Mods"
 header_components = table: 0x111c2238  {version:table: 0x111c3150, id:table: 0x111c2560, conflicts:table: 0x111c2f30 (more...)}
 json_spec = table: 0x111c4ea8  {provides:table: 0x1120b7d0, __:table: 0x1120ab28, version:table: 0x11203930 (more...)}
 used_prefixes = table: 0x1120be78  {csau:Cardsauce}
 lovely_directories = table: 0x1120bea0  {1:C:\Users\oshwa\AppData\Roaming\Balatro\Mods/Cardsauce-main/}
 processDirectory = Lua function '?' (defined at line 171 of chunk [SMODS _ "src/loader.lua"])
 keyset = table: 0x111abaa0  {1:0}
 check_dependencies = Lua function '?' (defined at line 408 of chunk [SMODS _ "src/loader.lua"])
 (for generator) = C function: builtin#6
 (for state) = table: 0x111abaa0  {1:0}
 (for control) = number: 1
 _ = number: 1
 priority = number: 0
 (for generator) = C function: builtin#6
 (for state) = table: 0x10ff31c8  {1:table: 0x10de7058}
 (for control) = number: 1
 _ = number: 1
 mod = table: 0x10de7058  {version:1.0, id:Cardsauce, main_file:main.lua, lovely:true, can_load:true (more...)}
(7) Lua global 'initSteamodded' at Steamodded file 'src/loader.lua:610' 
(8) Lua method 'start_up' at file 'game.lua:211'
Local variables:
 self = table: 0x10da6808  {loadTrophies:true, SPEEDFACTOR:1, F_GUIDE:false, keybind_mapping:table: 0x10db17f8 (more...)}
 settings = string: "return {[\"version\"]=\"1.0.1n-FULL\",[\"paused\"]=false,[\"QUEUED_CHANGE\"]={},[\"COMP\"]={[\"prev_name\"]=\"\",[\"name\"]=\"\",[\"score\"]=1266223,},[\"colourblind_option\"]=true,[\"play_button_pos\"]=2,[\"CUSTOM_DECK\"]={[\"Collabs\"]={[\"Spades\"]=\"collab_CYP\",[\"Hearts\"]=\"collab_TBoI\",[\"Diamonds\"]=\"collab_EG\",[\"Clubs\"]=\"collab_VS\",},},[\"language\"]=\"en-us\",[\"crashreports\"]=false,[\"tutorial_progress\"]={[\"hold_parts\"]={[\"first_hand_3\"]=true,[\"small_blind\"]=true,[\"big_blind\"]=true,[\"first_hand_4\"]=true,[\"second_hand\"]=true,[\"shop_1\"]=true,[\"first_hand_2\"]=true,[\"first_hand\"]=true,},[\"section\"]=\"second_hand\",[\"completed_parts\"]={[\"first_hand\"]=true,[\"first_hand_3\"]=true,[\"small_blind\"]=true,[\"big_blind\"]=true,[\"first_hand_4\"]=true,[\"shop_1\"]=true,[\"first_hand_section\"]=true,[\"first_hand_2\"]=true,[\"second_hand\"]=true,},},[\"tutorial_complete\"]=true,[\"run_stake_stickers\"]=false,[\"screenshake\"]=0,[\"WINDOW\"]={[\"vsync\"]=1,[\"display_names\"]={[1]=\"1\",},[\"screenmode\"]=\"Borderless\",[\"DISPLAYS\"]={[1]={[\"screen_resolutions\"]={[\"strings\"]={[1]=\"2736 X 1824\",},[\"values\"]={[1]={[\"w\"]=1368,[\"h\"]=912,},},},[\"screen_res\"]={[\"w\"]=1536,[\"h\"]=864,},[\"DPI_scale\"]=1,[\"MONITOR_DIMS\"]={[\"height\"]=1824,[\"width\"]=2736,},},},[\"selected_display\"]=1,},[\"GAMESPEED\"]=4,[\"no_mod_tracking\"]=false,[\"SOUND\"]={[\"volume\"]=50,[\"music_volume\"]=100,[\"game_sounds_volume\"]=100,},[\"music_control\"]={[\"current_track\"]=\"\",[\"desired_track\"]=\"\",[\"lerp\"]=1,},[\"ACHIEVEMENTS_EARNED\"]={[\"card_discarder\"]=true,[\"ach_cry_haxxor\"]=true,[\"heads_up\"]=true,[\"retrograde\"]=true,[\"royale\"]=true,[\"ach_cry_googol_play_pass\"]=true,[\"cartomancy\"]=true,[\"low_stakes\"]=true,[\"card_player\"]=true,[\"ante_upper\"]=true,[\"rule_bender\"]=true,[\"ach_cry_used_crash\"]=true,[\"ach_cry_now_the_fun_begins\"]=true,[\"ach_cry_break_infinity\"]=true,[\"legendary\"]=true,[\"ach_cry_pull_request\"]=true,[\"_10k\"]=true,[\"ach_cry_jokes_on_you\"]=true,[\"_1000k\"]=true,[\"ante_up\"]=true,[\"you_get_what_you_get\"]=true,},[\"profile\"]=3,[\"current_setup\"]=\"New Run\",[\"cryptid_notifs\"]={[\"jimball\"]=true,},[\"ambient_control\"]={[\"ambientFire1\"]={[\"per\"]=1.1,[\"vol\"]=2.2232954062856e-322,},[\"ambientOrgan1\"]={[\"per\"]=0.7,[\"vol\"]=2.2232954062856e-322,},[\"ambientFire2\"]={[\"per\"]=1.05,[\"vol\"]=2.2232954062856e-322,},[\"ambientFire3\"]={[\"per\"]=1,[\"vol\"]=2.2232954062856e-322,},},[\"DEMO\"]={[\"win_CTA_shown\"]=true,[\"quit_CTA_shown\"]=true,[\"timed_CTA_shown\"]=true,[\"total_uptime\"]=10991.513810479,},[\"GRAPHICS\"]={[\"texture_scaling\"]=2,[\"crt\"]=0,[\"shadows\"]=\"On\",[\"bloom\"]=1,},}"
 settings_ver = nil
 new_colour_proto = table: 0x10daf088  {Spades:table: 0x10daf2f0, Hearts:table: 0x10daf1a0, Diamonds:table: 0x10daf258 (more...)}
 sound_files = table: 0x1103ee18  {1:ambientFire1.ogg, 2:ambientFire2.ogg, 3:ambientFire3.ogg, 4:ambientOrgan1.ogg (more...)}
 shader_files = table: 0x10f21d40  {1:CRT.fs, 2:background.fs, 3:booster.fs, 4:debuff.fs, 5:dissolve.fs, 6:flame.fs (more...)}
(9) Lua field 'load' at file 'main.lua:945'
(10) Lua function '?' at file 'main.lua:892' (best guess)
(11) global C function 'xpcall'
(12) LÖVE function at file 'boot.lua:368' (best guess)
Local variables:
 result = boolean: true
 main = nil
(13) global C function 'xpcall'
(14) LÖVE function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '(LÖVE Function)' (defined at line 355 of chunk [love "boot.lua"])
 inerror = boolean: true
 deferErrhand = Lua function '(LÖVE Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(LÖVE Function)' (defined at line 355 of chunk [love "boot.lua"])

**Comment by BarrierTrio** [comment]
Make sure you open the zip and drag the Cardsauce file inside of it to your mods file (there should be one folder named Cardsauce, not one folder nested in another)

**Comment by Mysthaps** [comment]
(also, should be resolved with commit e4f5740)
