### ISSUE TITLE
Crash on startup. Fresh download.

### ISSUE THREAD

**Issue by foodismydeadname** [BarrierTrio/Cardsauce#6]
Oops! The game crashed:
[SMODS _ "src/game_object.lua"]:359: Failed to collect file data for Atlas csau_ods/Cardsauce-main/assets/1x/tarot//kermit

Additional Context:
Balatro Version: 1.0.1n-FULL
Modded Version: 1.0.0~ALPHA-1220a-STEAMODDED
LÖVE Version: 11.5.0
Lovely Version: 0.6.0
Steamodded Mods:
    1: Cardsauce by BarrierTrio/Gote & Keku [ID: Cardsauce, Version: 1.0, Uses Lovely]
Lovely Mods:

Stack Traceback
===============
(3) global C function 'assert'
(4) Lua method 'inject' at Steamodded file 'src/game_object.lua:359' 
Local variables:
 self = table: 0x1e038f28  {full_path:C:\Users\justj\AppData\Roaming\Balatro\Mods/Cardsauce-main/assets/2x/tarot/ods/Cardsauce-main/assets/1x/tarot//kermit.png (more...)}
 file_path = string: "tarot/ods/Cardsauce-main/assets/1x/tarot//kermit.png"
(5) Lua method 'inject_class' at Steamodded file 'src/game_object.lua:182' 
Local variables:
 self = table: 0x1de84e48  {required_params:table: 0x1de84a50, pre_inject_class:function: 0x1de84e28 (more...)}
 inject_time = number: 0.376499
 start_time = number: 7.2154
 end_time = number: 7.2154
 o = table: 0x1e038f28  {full_path:C:\Users\justj\AppData\Roaming\Balatro\Mods/Cardsauce-main/assets/2x/tarot/ods/Cardsauce-main/assets/1x/tarot//kermit.png (more...)}
 (for generator) = C function: builtin#6
 (for state) = table: 0x1de84a28  {1:mod_tags, 2:achievements, 3:csau_meat, 4:csau_twoface, 5:csau_newjoker (more...)}
 (for control) = number: 72
 i = number: 72
 key = string: "csau_ods/Cardsauce-main/assets/1x/tarot//kermit"
(6) Lua field 'injectObjects' at Steamodded file 'src/game_object.lua:252' 
Local variables:
 class = table: 0x1de84e48  {required_params:table: 0x1de84a50, pre_inject_class:function: 0x1de84e28 (more...)}
(7) Lua field 'injectObjects' at Steamodded file 'src/game_object.lua:254' 
Local variables:
 class = table: 0x1de83d20  {check_duplicate_register:function: 0x1de83f58, check_duplicate_key:function: 0x1de83f78 (more...)}
 (for generator) = C function: builtin#6
 (for state) = table: 0x1de83de8  {1:table: 0x1de84608, 2:table: 0x1de84988, 3:table: 0x1de84e48, 4:table: 0x1de859c0 (more...)}
 (for control) = number: 3
 _ = number: 3
 subclass = table: 0x1de84e48  {required_params:table: 0x1de84a50, pre_inject_class:function: 0x1de84e28 (more...)}
(8) Lua field 'injectItems' at Steamodded file 'src/loader.lua:564' 
(9) Lua global 'initSteamodded' at Steamodded file 'src/loader.lua:614' 
(10) Lua method 'start_up' at file 'game.lua:211'
Local variables:
 self = table: 0x1d7ae640  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, F_ENGLISH_ONLY:false (more...)}
 settings = string: "return {[\"version\"]=\"1.0.1n-FULL\",[\"paused\"]=true,[\"QUEUED_CHANGE\"]={},[\"COMP\"]={[\"prev_name\"]=\"\",[\"name\"]=\"\",[\"score\"]=1512553383.4461,},[\"colourblind_option\"]=false,[\"play_button_pos\"]=2,[\"CUSTOM_DECK\"]={[\"Collabs\"]={[\"Spades\"]=\"collab_DS\",[\"Hearts\"]=\"collab_CL\",[\"Diamonds\"]=\"default\",[\"Clubs\"]=\"collab_PC\",},},[\"STATUSTEXT\"]=0,[\"language\"]=\"en-us\",[\"crashreports\"]=false,[\"tutorial_progress\"]={[\"hold_parts\"]={[\"first_hand_3\"]=true,[\"second_hand\"]=true,[\"big_blind\"]=true,[\"first_hand_4\"]=true,[\"small_blind\"]=true,[\"shop_1\"]=true,[\"first_hand_2\"]=true,[\"first_hand\"]=true,},[\"section\"]=\"second_hand\",[\"completed_parts\"]={[\"first_hand\"]=true,[\"first_hand_3\"]=true,[\"second_hand\"]=true,[\"big_blind\"]=true,[\"first_hand_4\"]=true,[\"small_blind\"]=true,[\"first_hand_section\"]=true,[\"first_hand_2\"]=true,[\"shop_1\"]=true,},},[\"run_stake_stickers\"]=true,[\"profile\"]=1,[\"screenshake\"]=20.778143176248,[\"WINDOW\"]={[\"vsync\"]=1,[\"display_names\"]={[1]=\"1\",},[\"screenmode\"]=\"Windowed\",[\"DISPLAYS\"]={[1]={[\"screen_resolutions\"]={[\"strings\"]={[1]=\"-\",},[\"values\"]={[1]={[\"w\"]=1280,[\"h\"]=720,},},},[\"screen_res\"]={[\"w\"]=1920,[\"h\"]=1080,},[\"DPI_scale\"]=1,[\"MONITOR_DIMS\"]={[\"height\"]=2160,[\"width\"]=3840,},},},[\"selected_display\"]=1,},[\"GAMESPEED\"]=4,[\"cryptid_notifs\"]={[\"jimball\"]=true,},[\"SOUND\"]={[\"volume\"]=65.451246471651,[\"music_volume\"]=70.544842035549,[\"game_sounds_volume\"]=70.128171479773,},[\"music_control\"]={[\"current_track\"]=\"\",[\"desired_track\"]=\"\",[\"lerp\"]=1,},[\"ACHIEVEMENTS_EARNED\"]={[\"card_discarder\"]=true,[\"heads_up\"]=true,[\"retrograde\"]=true,[\"roi\"]=true,[\"_100000k\"]=true,[\"cartomancy\"]=true,[\"mid_stakes\"]=true,[\"low_stakes\"]=true,[\"nest_egg\"]=true,[\"astronomy\"]=true,[\"ante_upper\"]=true,[\"_1000k\"]=true,[\"ach_cry_used_crash\"]=true,[\"speedrunner\"]=true,[\"_10k\"]=true,[\"extreme_couponer\"]=true,[\"shattered\"]=true,[\"legendary\"]=true,[\"royale\"]=true,[\"clairvoyance\"]=true,[\"ante_up\"]=true,[\"card_player\"]=true,},[\"tutorial_complete\"]=true,[\"current_setup\"]=\"New Run\",[\"ambient_control\"]={[\"ambientFire1\"]={[\"per\"]=1.1,[\"vol\"]=0,},[\"ambientOrgan1\"]={[\"per\"]=0.7,[\"vol\"]=0,},[\"ambientFire2\"]={[\"per\"]=1.05,[\"vol\"]=0,},[\"ambientFire3\"]={[\"per\"]=1,[\"vol\"]=0,},[\"jen_ambientSurreal3\"]={[\"per\"]=1,[\"vol\"]=0,},[\"jen_ambientDramatic\"]={[\"per\"]=1,[\"vol\"]=0,},[\"jen_ambientSurreal2\"]={[\"per\"]=1,[\"vol\"]=0,},[\"jen_ambientSurreal1\"]={[\"per\"]=1,[\"vol\"]=0,},},[\"FASTFORWARD\"]=0,[\"DEMO\"]={[\"win_CTA_shown\"]=true,[\"quit_CTA_shown\"]=true,[\"timed_CTA_shown\"]=true,[\"total_uptime\"]=20.069905660634,},[\"GRAPHICS\"]={[\"bloom\"]=1,[\"crt\"]=101,[\"texture_scaling\"]=2,[\"shadows\"]=\"On\",},}"
 settings_ver = nil
 new_colour_proto = table: 0x1d7b6be8  {Spades:table: 0x1e0308b0, Hearts:table: 0x1e030988, Diamonds:table: 0x1e030a60 (more...)}
 sound_files = table: 0x1d79de58  {1:ambientFire1.ogg, 2:ambientFire2.ogg, 3:ambientFire3.ogg, 4:ambientOrgan1.ogg (more...)}
 shader_files = table: 0x1d79b0c0  {1:CRT.fs, 2:background.fs, 3:booster.fs, 4:debuff.fs, 5:dissolve.fs, 6:flame.fs (more...)}
(11) Lua field 'load' at file 'main.lua:945'
(12) Lua function '?' at file 'main.lua:892' (best guess)
(13) global C function 'xpcall'
(14) LÖVE function at file 'boot.lua:368' (best guess)
Local variables:
 result = boolean: true
 main = nil
(15) global C function 'xpcall'
(16) LÖVE function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '(LÖVE Function)' (defined at line 355 of chunk [love "boot.lua"])
 inerror = boolean: true
 deferErrhand = Lua function '(LÖVE Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(LÖVE Function)' (defined at line 355 of chunk [love "boot.lua"])

**Comment by SEAGULLaahh** [comment]
I just got the same error myself, too.

**Comment by BarrierTrio** [comment]
It looks like somehow files from the mod got nested inside of other files? Try a fresh download and be sure to open the zip and drag the one file inside to the mods folder (don't unzip it in the mods folder)

**Comment by foodismydeadname** [comment]
It worked, idk if it was updated or I was foolish but it worked, thank you!

**Comment by Octopasta98** [comment]
Hey, I have this exact same error. Line for line, bar for bar. 

I tried BarrierTrio's recommendation to fresh download it again. I even removed

The problem is; the file path calling for the Kermit Tarot is, in fact, there. 

I removed the mods and verified Balatro file integrity before reinstalling the mods (Only the bare necessities and nothing else required for Cardsauce).

Any ideas on how to fix this? The file its looking for is in the right place, in the right file format.

![image](https://github.com/user-attachments/assets/6bffd869-f2d0-4f3f-b8d9-2d661ffb6f1d)
![image_2024-12-21_102813067](https://github.com/user-attachments/assets/ff452c7b-50ea-47e9-b352-2143f1b9641f)

**Comment by Kekulism** [comment]
This is a steammodded bug caused by the '-main' in the folder name, a remnant from the github repo download. I've added a note to the install instructions for the mod. 

"**NOTE:** If you are downloading the mod using the source code and not the release download, **always remember to remove '-main' from the folder name for Cardsauce!** You may run into issues if it's not removed."

We recommend downloading the mod from the release pages, it comes with the corrected folder name already included.
