### ISSUE TITLE
Error on Startup, Fresh Steammodded injection

### ISSUE THREAD

**Issue by thegenn** [BarrierTrio/Cardsauce#8]
Here is the Error In question:
----

Error

Syntax error: game.lua:4: '=' expected near 'Game'

Traceback

[love "callbacks.lua"]:228: in function 'handler'
[C]: at 0x7ffa21672fa0
[C]: in function 'require'
main.lua:14: in main chunk
[C]: in function 'require'
[C]: in function 'xpcall'
[C]: in function 'xpcall'

----
I have many other mods, some that require lovely, and they work fine. Why doesn't this one?
(probably because it's really really big but I digress)

**Comment by Kekulism** [comment]
Since Cardsauce gets a bit high concept in a lot of areas, we cannot guarantee compatibility with all mods. Without knowing what mods you're using I'm not sure how to help. I will say though that I've seen evidence that Cryptid is not compatible with Cardsauce, so if you're using that, that may be the issue. Still not sure though

**Comment by musicrocks1** [comment]
Having a very similar issue with a fresh install of everything, here's the crash dump.

Oops! The game crashed:
[SMODS _ "src/game_object.lua"]:359: Failed to collect file data for Atlas csau_ods/Cardsauce-main/assets/1x/tarot//kermit

Additional Context:
Balatro Version: 1.0.1n-FULL
Modded Version: 1.0.0~ALPHA-1221d-STEAMODDED
LÖVE Version: 11.5.0
Lovely Version: 0.6.0
Steamodded Mods:
    1: Cardsauce by BarrierTrio/Gote & Keku [ID: Cardsauce, Version: 1.0, Uses Lovely]
Lovely Mods:

Stack Traceback
===============
(3) global C function 'assert'
(4) Lua method 'inject' at Steamodded file 'src/game_object.lua:359' 
Local variables:
 self = table: 0x286559a0  {full_path:C:\Users\johhn\AppData\Roaming\Balatro\Mods/Cardsauce-main/assets/2x/tarot/ods/Cardsauce-main/assets/1x/tarot//kermit.png (more...)}
 file_path = string: "tarot/ods/Cardsauce-main/assets/1x/tarot//kermit.png"
(5) Lua method 'inject_class' at Steamodded file 'src/game_object.lua:182' 
Local variables:
 self = table: 0x284f9bc0  {required_params:table: 0x284f97c8, pre_inject_class:function: 0x284f9ba0 (more...)}
 inject_time = number: 0.559564
 start_time = number: 7.29437
 end_time = number: 7.29437
 o = table: 0x286559a0  {full_path:C:\Users\johhn\AppData\Roaming\Balatro\Mods/Cardsauce-main/assets/2x/tarot/ods/Cardsauce-main/assets/1x/tarot//kermit.png (more...)}
 (for generator) = C function: builtin#6
 (for state) = table: 0x284f97a0  {1:mod_tags, 2:achievements, 3:csau_meat, 4:csau_twoface, 5:csau_newjoker (more...)}
 (for control) = number: 72
 i = number: 72
 key = string: "csau_ods/Cardsauce-main/assets/1x/tarot//kermit"
(6) Lua field 'injectObjects' at Steamodded file 'src/game_object.lua:252' 
Local variables:
 class = table: 0x284f9bc0  {required_params:table: 0x284f97c8, pre_inject_class:function: 0x284f9ba0 (more...)}
(7) Lua field 'injectObjects' at Steamodded file 'src/game_object.lua:254' 
Local variables:
 class = table: 0x284f8a98  {check_duplicate_register:function: 0x284f8cd0, check_duplicate_key:function: 0x284f8cf0 (more...)}
 (for generator) = C function: builtin#6
 (for state) = table: 0x284f8b60  {1:table: 0x284f9380, 2:table: 0x284f9700, 3:table: 0x284f9bc0, 4:table: 0x284fa738 (more...)}
 (for control) = number: 3
 _ = number: 3
 subclass = table: 0x284f9bc0  {required_params:table: 0x284f97c8, pre_inject_class:function: 0x284f9ba0 (more...)}
(8) Lua field 'injectItems' at Steamodded file 'src/loader.lua:564' 
(9) Lua global 'initSteamodded' at Steamodded file 'src/loader.lua:614' 
(10) Lua method 'start_up' at file 'game.lua:211'
Local variables:
 self = table: 0x27f1dc58  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, F_ENGLISH_ONLY:false (more...)}
 settings = string: "return {[\"version\"]=\"1.0.1m-FULL\",[\"paused\"]=false,[\"QUEUED_CHANGE\"]={},[\"COMP\"]={[\"prev_name\"]=\"\",[\"name\"]=\"\",[\"score\"]=1863198.72,},[\"colourblind_option\"]=true,[\"play_button_pos\"]=2,[\"CUSTOM_DECK\"]={[\"Collabs\"]={[\"Spades\"]=\"collab_TW\",[\"Hearts\"]=\"collab_TBoI\",[\"Diamonds\"]=\"collab_SV\",[\"Clubs\"]=\"collab_VS\",},},[\"crashreports\"]=false,[\"tutorial_progress\"]={[\"hold_parts\"]={[\"first_hand_3\"]=true,[\"shop_1\"]=true,[\"big_blind\"]=true,[\"first_hand_4\"]=true,[\"small_blind\"]=true,[\"second_hand\"]=true,[\"first_hand_2\"]=true,[\"first_hand\"]=true,},[\"section\"]=\"second_hand\",[\"completed_parts\"]={[\"first_hand\"]=true,[\"first_hand_3\"]=true,[\"shop_1\"]=true,[\"big_blind\"]=true,[\"first_hand_4\"]=true,[\"small_blind\"]=true,[\"first_hand_section\"]=true,[\"first_hand_2\"]=true,[\"second_hand\"]=true,},},[\"language\"]=\"en-us\",[\"profile\"]=1,[\"WINDOW\"]={[\"vsync\"]=1,[\"display_names\"]={[1]=\"[NONE]\",},[\"screenmode\"]=\"Borderless\",[\"DISPLAYS\"]={[1]={[\"name\"]=\"[NONE]\",[\"screen_res\"]={[\"w\"]=1920,[\"h\"]=1080,},},},[\"selected_display\"]=1,},[\"run_stake_stickers\"]=false,[\"GAMESPEED\"]=4,[\"SOUND\"]={[\"volume\"]=50,[\"music_volume\"]=100,[\"game_sounds_volume\"]=100,},[\"music_control\"]={[\"current_track\"]=\"\",[\"desired_track\"]=\"\",[\"lerp\"]=1,},[\"ACHIEVEMENTS_EARNED\"]={[\"ante_upper\"]=true,[\"_10k\"]=true,[\"_1000k\"]=true,[\"ante_up\"]=true,[\"heads_up\"]=true,},[\"screenshake\"]=50,[\"current_setup\"]=\"New Run\",[\"ambient_control\"]={[\"ambientFire3\"]={[\"per\"]=1,[\"vol\"]=1.581010066692e-322,},[\"ambientFire1\"]={[\"per\"]=1.1,[\"vol\"]=1.581010066692e-322,},[\"ambientFire2\"]={[\"per\"]=1.05,[\"vol\"]=1.581010066692e-322,},[\"ambientOrgan1\"]={[\"per\"]=0.7,[\"vol\"]=1.581010066692e-322,},},[\"tutorial_complete\"]=true,[\"DEMO\"]={[\"win_CTA_shown\"]=true,[\"quit_CTA_shown\"]=true,[\"timed_CTA_shown\"]=true,[\"total_uptime\"]=4019.5511596785,},[\"GRAPHICS\"]={[\"bloom\"]=1,[\"crt\"]=70,[\"shadows\"]=\"On\",[\"texture_scaling\"]=2,},}"
 settings_ver = nil
 new_colour_proto = table: 0x27f26570  {Spades:table: 0x285fefd8, Hearts:table: 0x285ff0b0, Diamonds:table: 0x285ff188 (more...)}
 sound_files = table: 0x27f1e488  {1:ambientFire1.ogg, 2:ambientFire2.ogg, 3:ambientFire3.ogg, 4:ambientOrgan1.ogg (more...)}
 shader_files = table: 0x27f0c5d8  {1:CRT.fs, 2:background.fs, 3:booster.fs, 4:debuff.fs, 5:dissolve.fs, 6:flame.fs (more...)}
(11) Lua field 'load' at file 'main.lua:945'
(12) Lua function '?' at file 'main.lua:892' (best guess)
(13) global C function 'xpcall'
(14) LÖVE function at file 'boot.lua:368' (best guess)
Local variables:
 result = boolean: true
 main = nil
(15) global C function 'xpcall'
(16) LÖVE function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '(LÖVE Function)' (defined at line 355 of chunk [love "boot.lua"])
 inerror = boolean: true
 deferErrhand = Lua function '(LÖVE Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(LÖVE Function)' (defined at line 355 of chunk [love "boot.lua"])

**Comment by thegenn** [comment]
I'm not trying to open with other mods, i was just providing a comaparison that it's not an issue on my end. I have only tried to intitalize the mod on its own, without any others to interfere.

**Comment by Mysthaps** [comment]
@thegenn You have Steamodded 0.9.8 installed, please verify your game files on Steam and redownload Steamodded, instructions [here](https://github.com/Steamopollys/Steamodded/wiki)

**Comment by Mysthaps** [comment]
@musicrocks1 Please rename your mod folder from ``Cardsauce-main`` to ``Cardsauce``

**Comment by thegenn** [comment]
That seemed to do the trick. Thank you, and good work!
