### ISSUE TITLE
New Jokers not loading with descriptions + New custom cards not loading

### ISSUE THREAD

**Issue by Octopasta98** [BarrierTrio/Cardsauce#9]
This is a pretty self-explanatory issue. I've got a clean install of this mod. However, none of the new cards load in the customization settings (outside of custom Aces).  

Additionally, when trying this out, all the new Jokers that were added have a blank name and description when you click on them.

Additionally, I have no other mods installed except for Steammodded, Lovely, and Cardsauce.

![image_2024-12-21_163316435](https://github.com/user-attachments/assets/dd32280c-a37e-422d-b954-ff01518249a2)

![image_2024-12-21_163535568](https://github.com/user-attachments/assets/d8084673-201a-449f-ae45-8c407bbdf7ee)

**Comment by Kekulism** [comment]
Update Steammodded to the latest version
